security:
    oauth2:
        client:
            access-token-uri: https://dev-370968.oktapreview.com/oauth2/default/v1/token
            user-authorization-uri: https://dev-370968.oktapreview.com/oauth2/default/v1/authorize
            client-id: 0oafv8pdgtY97f1PK0h7
            scope: openid profile username
        resource:
            user-info-uri: https://dev-370968.oktapreview.com/oauth2/default/v1/userinfo
            token-info-uri: https://dev-370968.oktapreview.com/default/v1/introspect
            prefer-token-info: false
            prefer-token-info: false